name: Auto-Poster
on:
  schedule:
    # Запуск каждый день в 08:00, 10:00, 12:00, 14:00, 16:00, 18:00, 20:00 и 22:00 по UTC
    - cron: '0 8,10,12,14,16,18,20,22 * * *'
  workflow_dispatch: # Позволяет нам запускать скрипт вручную для тестов

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run main script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
        run: python main.py
